# Generated by Django 3.0 on 2020-02-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailid', models.EmailField(max_length=254)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=50)),
                ('status', models.CharField(blank=True, default='off', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mobileno', models.CharField(max_length=12)),
                ('emailid', models.EmailField(max_length=254)),
                ('types', models.CharField(max_length=20)),
                ('officeadd', models.CharField(max_length=30)),
                ('residenceadd', models.CharField(max_length=30)),
                ('joiningdate', models.DateField()),
                ('duration', models.CharField(max_length=20)),
                ('approvedate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('expirydate', models.DateField(blank=True, default='2020-12-12', null=True)),
            ],
        ),
    ]
